{{- define "Deployment-toolbox" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "helpers.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "helpers.labels.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{ include "helpers.pod.node_selector" ( dict "Global" $ "Application" "toolbox" ) | nindent 8 }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-ceph-tools
        image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "toolbox" ) }}
        imagePullPolicy: {{ .Values.images.pull.policy | quote }}
        command: ["/tini"]
        args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
        env:
          - name: ROOK_CEPH_USERNAME
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: ceph-username
          - name: ROOK_CEPH_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: ceph-secret
        volumeMounts:
          - mountPath: /etc/ceph
            name: ceph-config
          - name: mon-endpoint-volume
            mountPath: /etc/rook
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: ceph-config
          emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Deployment-toolbox" ) }}
