images:
  applications:
    toolbox:
      tag: v1.5.4
      name: rook/ceph
      repo: docker.io
  pull:
    policy: IfNotPresent

node_labels:
  toolbox:
    key: kubernetes-apiserver
    value: "enabled"

rook-ceph:
  image:
    prefix: rook
    repository: rook/ceph
    tag: v1.5.4
    pullPolicy: IfNotPresent
  csi:
    cephfsGrpcMetricsPort: 9092
    cephfsLivenessMetricsPort: 9082
    cephcsi:
      image: quay.io/cephcsi/cephcsi:v3.2.0
    registrar:
      image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
    provisioner:
      image: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.0
    snapshotter:
      image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.0
    attacher:
      image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
    resizer:
      image: k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
  nodeSelector:
    kubernetes-apiserver: "enabled"

# requires:
# - nginx ingress
# - cert manager
# - nginx-cluster ingress class
dashboard_ingress:
  enabled: true

over_rides:
  deployment:
    toolbox: null
  ingress:
    dashboard:
      spec:
        tls:
          - hosts:
            - rook-ceph.example.com
            secretName: rook-ceph.example.com
        rules:
          - host: rook-ceph.example.com
            http:
              paths:
                - path: /
                  backend:
                    serviceName: rook-ceph-mgr-dashboard
                    servicePort: https-dashboard

  cephblockpool:
    default:
      spec:
        # For "rack" failure domain the following node label is required:
        # topology.rook.io/rack=rackname
        failureDomain: rack
        replicated:
          size: 3
          requireSafeReplicaSize: true
  cephfilesystem:
    default:
      spec:
        metadataPool:
          # For "rack" failure domain the following node label is required:
          # topology.rook.io/rack=rackname
          failureDomain: rack
          replicated:
            size: 3
            requireSafeReplicaSize: true
        dataPools:
          # For "rack" failure domain the following node label is required:
          # topology.rook.io/rack=rackname
          - failureDomain: rack
            replicated:
              size: 3
              requireSafeReplicaSize: true
  cephcluster:
    default:
      spec:
        dataDirHostPath: /var/lib/rook
        cephVersion:
          image: ceph/ceph:v15.2.8
          allowUnsupported: true
        mon:
          count: 3
          allowMultiplePerNode: false
        dashboard:
          enabled: true
          ssl: true
          port: 8443
        network:
          provider: host
        crashCollector:
          disable: true
        # TODO? placement
        # https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#placement-configuration-settings
        storage:
          useAllNodes: false
          useAllDevices: false
          nodes:
          #  - name: node1
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
          #  - name: node2
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
          #  - name: node3
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
          #  - name: node4
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
          #  - name: node5
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
          #  - name: node6
          #    devices:
          #      - name: sdd
          #      - name: sde
          #      - name: sdf
          #      - name: sdg
          #      - name: sdh
          #      - name: sdi
          #      - name: sdj
          #      - name: sdk
          #      - name: sdl
